=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/residences/clanHalls/clanHall.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../../xsd/common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="clanHall" type="ClanHall" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ClanHall">
		<xs:sequence>
			<xs:element name="auction">
				<xs:complexType>
					<xs:attribute type="xs:string" name="min-bid" use="required" />
					<xs:attribute type="xs:string" name="lease" use="required" />
					<xs:attribute type="xs:string" name="deposit" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="npcs" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="npc" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:attribute type="xs:int" name="id"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="doors" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="door" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:positiveInteger" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ownerRestartPoint" type="Location"/>
			<xs:element name="banishPoint" type="Location"/>
		</xs:sequence>
		<xs:attribute type="xs:short" name="id" use="required" />
		<xs:attribute type="xs:string" name="name" />
		<xs:attribute name="grade" type="CrystalType"/>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="AUCTIONABLE" />
					<xs:enumeration value="SIEGEABLE" />
					<xs:enumeration value="INSTANCED" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/residences/clanHalls/dion.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org clanHall.xsd" >

    <clanHall id="31" name="The Atramental Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000" deposit="500000" />
        <npcs>
            <npc id="35402" /> <!-- Borna -->
            <npc id="35403" /> <!-- Ron -->
        </npcs>
        <doors>
            <door id="20220013" />
            <door id="20220014" />
        </doors>
        <ownerRestartPoint x="17760" y="145200" z="-3036" />
        <banishPoint x="17552" y="145248" z="-3050" />
    </clanHall>

    <clanHall id="32" name="Scarlet Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000" deposit="500000" />
        <npcs>
            <npc id="35404" /> <!-- Jamael -->
            <npc id="35405" /> <!-- Flynn -->
        </npcs>
        <doors>
            <door id="20220011" />
            <door id="20220012" />
        </doors>
        <ownerRestartPoint x="18800" y="143248" z="-3010" />
        <banishPoint x="18976" y="143360" z="-3033" />
    </clanHall>

    <clanHall id="33" name="Viridian Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000" deposit="500000" />
        <npcs>
            <npc id="35406" /> <!-- Jabilo -->
            <npc id="35407" /> <!-- Seth -->
        </npcs>
        <doors>
            <door id="20220016" />
            <door id="20220015" />
        </doors>
        <ownerRestartPoint x="20096" y="146064" z="-3111" />
        <banishPoint x="20192" y="145920" z="-3125" />
    </clanHall>

    <clanHall id="69" name="Blue Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000" deposit="500000" />
        <npcs>
            <npc id="36730" /> <!-- Faolin -->
            <npc id="36729" /> <!-- Bremen -->
        </npcs>
        <doors>
            <door id="20220120" />
            <door id="20220119" />
        </doors>
        <ownerRestartPoint x="16370" y="155983" z="-3617" />
        <banishPoint x="16208" y="155285" z="-3640" />
    </clanHall>

    <clanHall id="70" name="Brown Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000" deposit="500000" />
        <npcs>
            <npc id="36732" /> <!-- Coren -->
            <npc id="36731" /> <!-- Kalein -->
        </npcs>
        <doors>
            <door id="20220122" />
            <door id="20220121" />
        </doors>
        <ownerRestartPoint x="15414" y="156067" z="-3619" />
        <banishPoint x="16208" y="155285" z="-3640" />
    </clanHall>

    <clanHall id="71" name="Yellow Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000" deposit="500000" />
        <npcs>
            <npc id="36734" /> <!-- Muren -->
            <npc id="36733" /> <!-- Winsnun -->
        </npcs>
        <doors>
            <door id="20220124" />
            <door id="20220123" />
        </doors>
        <ownerRestartPoint x="14501" y="155408" z="-3503" />
        <banishPoint x="16208" y="155285" z="-3640" />
    </clanHall>

    <clanHall id="72" name="White Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000" deposit="500000" />
        <npcs>
            <npc id="36736" /> <!-- Lenning -->
            <npc id="36735" /> <!-- Yuven -->
        </npcs>
        <doors>
            <door id="20220126" />
            <door id="20220125" />
        </doors>
        <ownerRestartPoint x="15816" y="154666" z="-3616" />
        <banishPoint x="16208" y="155285" z="-3640" />
    </clanHall>

</list>
