=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/augmentation/options/options.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../../skills/effects.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="option" type="Option" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Option">
		<xs:sequence>
			<xs:element name="effects" type="Effects" minOccurs="0"/>
			<xs:element name="skill" type="OptionSkill" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
		<xs:attribute type="xs:token" name="name" use="required" />
	</xs:complexType>

	<xs:complexType name="OptionSkill">
		<xs:complexContent>
			<xs:extension base="ChancedSkillInfo">
				<xs:attribute name="type" type="OptionSkillType" default="ACTIVE"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="OptionSkillType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="ATTACK"/>
			<xs:enumeration value="MAGIC"/>
			<xs:enumeration value="CRITICAL"/>
			<xs:enumeration value="ACTIVE"/>
			<xs:enumeration value="PASSIVE"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/augmentation/options/22800-22899.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org options.xsd">
    <option id="22883" name="o_s_82_2s_1">
        <!-- Active: Head size increases temporarily. Increase. -->
        <skill id="3203"/> <!-- Item Skill: Mystery Skill -->
    </option>
    <option id="22884" name="o_s_82_2s_2">
        <!-- Active: Temporarily increases lung capacity. -->
        <skill id="3143" level="10"/> <!-- Item Skill: Kiss of Eva -->
    </option>
    <option id="22885" name="o_s_82_2s_3">
        <!-- Active: Increases the height from which you can jump without sustaining damage for a fixed time. -->
        <skill id="3144" level="10"/> <!-- Item Skill: Acrobatics -->
    </option>
    <option id="22886" name="o_s_82_2s_4">
        <!-- Active: Increases Resistance to damage from falling. -->
        <skill id="3145" level="10"/> <!-- Item Skill: Iron Body -->
    </option>
    <option id="22887" name="o_s_82_2s_5">
        <!-- Active: Ignites a firecracker. -->
        <skill id="3156"/> <!-- Item Skill: Firework -->
    </option>
    <option id="22888" name="o_s_82_2s_6">
        <!-- Active: Temporarily plays music. -->
        <skill id="3206"/> <!-- Item Skill: Music -->
    </option>
    <option id="22889" name="o_s_82_2s_7">
        <!-- Active: Ignites a large firecracker. -->
        <skill id="3157"/> <!-- Item Skill: Large Firework -->
    </option>
    <option id="22890" name="o_s_82_2s_8">
        <!-- Chance: During a physical attack, temporarily decreases the target's attacking desire for oneself. -->
        <skill id="3081" level="10" chance="1.0" type="ATTACK"/> <!-- Item Skill: Charm -->
    </option>
    <option id="22891" name="o_s_82_2s_9">
        <!-- Chance: During a physical attack, temporarily stimulates the target's attacking desire. -->
        <skill id="3080" level="10" chance="1.0" type="ATTACK"/> <!-- Item Skill: Aggression -->
    </option>
    <option id="22892" name="o_s_82_2s_10">
        <!-- Chance: During a physical attack, temporarily decreases the target's moving speed. -->
        <skill id="3083" level="10" chance="1.0" type="ATTACK"/> <!-- Item Skill: Slow -->
    </option>
    <option id="22893" name="o_s_82_2s_11">
        <!-- Chance: During a critical attack, temporarily decreases the target's attacking desire for oneself. -->
        <skill id="3109" level="10" chance="5.0" type="CRITICAL"/> <!-- Item Skill: Aggression Down -->
    </option>
    <option id="22894" name="o_s_82_2s_12">
        <!-- Chance: During a critical attack, temporarily stimulates the target's attacking desire. -->
        <skill id="3108" level="10" chance="5.0" type="CRITICAL"/> <!-- Item Skill: Aggression Up -->
    </option>
    <option id="22895" name="o_s_82_2s_13">
        <!-- Chance: During a critical attack, temporarily decreases the target's moving speed. -->
        <skill id="3111" level="10" chance="5.0" type="CRITICAL"/> <!-- Item Skill: Slow -->
    </option>
    <option id="22896" name="o_s_82_2s_14">
        <!-- Chance: Instantly decreases a target's moving speed during a magic attack. Effect 3. -->
        <skill id="3096" level="10" chance="2.0" type="MAGIC"/> <!-- Item Skill: Slow -->
    </option>
    <option id="22897" name="o_s_82_2s_15">
        <!-- Passive: Increases lung capacity. -->
        <skill id="3252" level="10" type="PASSIVE"/> <!-- Item Skill: Kiss of Eva -->
    </option>
    <option id="22898" name="o_s_82_2s_16">
        <!-- Passive: Increases the height from which you can jump without sustaining damage. -->
        <skill id="3253" level="10" type="PASSIVE"/> <!-- Item Skill: Acrobatics -->
    </option>
    <option id="22899" name="o_s_82_2s_17">
        <!-- Passive: Increases Resistance to damage from falling. -->
        <skill id="3254" level="10" type="PASSIVE"/> <!-- Item Skill: Iron Body -->
    </option>
</list>

=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/augmentation/options/15000-15099.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org options.xsd">
    <option id="15095" name="o_s_55_2s_1">
        <!-- Passive: Increases the recovery rate when MP is being recovered by recharge. -->
        <skill id="3203"/> <!-- Item Skill: Mystery Skill -->
    </option>
    <option id="15096" name="o_s_55_2s_2">
        <!-- Active: Temporarily increases lung capacity. -->
        <skill id="3143" level="4"/> <!-- Item Skill: Kiss of Eva -->
    </option>
    <option id="15097" name="o_s_55_2s_3">
        <!-- Active: Increases the height from which you can jump without sustaining damage for a fixed time. -->
        <skill id="3144" level="4"/> <!-- Item Skill: Acrobatics -->
    </option>
    <option id="15098" name="o_s_55_2s_4">
        <!-- Active: Increases Resistance to damage from falling. -->
        <skill id="3145" level="4"/> <!-- Item Skill: Iron Body -->
    </option>
    <option id="15099" name="o_s_55_2s_5">
        <!-- Active: Ignites a firecracker. -->
        <skill id="3156"/> <!-- Item Skill: Firework -->
    </option>
</list>
