=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/xsd/ensoulStones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fee" type="EnsoulFee" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element name="stone" type="EnsoulStone" maxOccurs="unbounded" minOccurs="0"/>
				<xs:element name="option" type="EnsoulOption" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="EnsoulOption">
		<xs:attribute type="xs:positiveInteger" name="id" use="required" />
		<xs:attribute type="xs:string" name="name" use="required" />
		<xs:attribute type="xs:string" name="desc" use="required" />
		<xs:attribute type="xs:positiveInteger" name="skillId" use="required" />
		<xs:attribute type="xs:positiveInteger" name="skillLevel" use="required" />
	</xs:complexType>

	<xs:complexType name="EnsoulStone">
		<xs:sequence>
			<xs:element name="option" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:attribute type="xs:positiveInteger" name="id" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:int" name="id" use="required" />
		<xs:attribute type="xs:byte" name="slotType" use="required" />
	</xs:complexType>

	<xs:complexType name="EnsoulFee">
		<xs:sequence>
			<xs:element name="first" minOccurs="0" type="feeItem" />
			<xs:element name="secondary" minOccurs="0" type="feeItem" />
			<xs:element name="third" minOccurs="0" type="feeItem" />
			<xs:element name="reNormal" minOccurs="0" type="feeItem" />
			<xs:element name="reSecondary" minOccurs="0" type="feeItem" />
			<xs:element name="reThird" minOccurs="0" type="feeItem" />
			<xs:element name="remove" minOccurs="0" maxOccurs="unbounded" type="feeItem" />
		</xs:sequence>
		<xs:attribute type="CrystalType" name="crystalType" use="required" />
	</xs:complexType>

	<xs:complexType name="feeItem">
		<xs:attribute type="xs:positiveInteger" name="itemId"/>
		<xs:attribute type="xs:positiveInteger" name="count"/>
	</xs:complexType>


</xs:schema>

=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/stats/ensoulStones.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../xsd/ensoulStones.xsd">

    <fee crystalType="D">
        <first itemId="2130" count="107"/> <!-- Gemstone (D-grade-grade) -->
        <secondary itemId="2130" count="107"/> <!-- Gemstone (D-grade-grade) -->
        <third itemId="2130" count="107"/> <!-- Gemstone (D-grade-grade) -->
        <reNormal itemId="2130" count="89"/> <!-- Gemstone (D-grade) -->
        <reSecondary itemId="2130" count="89"/> <!-- Gemstone (D-grade) -->
        <reThird itemId="2130" count="89"/> <!-- Gemstone (D-grade) -->
        <remove itemId="2130" count="89"/> <!-- Gemstone (D-grade) -->
    </fee>

    <fee crystalType="C">
        <first itemId="2131" count="177"/> <!-- Gemstone (C-grade) -->
        <secondary itemId="2131" count="177"/> <!-- Gemstone (C-grade) -->
        <third itemId="2131" count="177"/> <!-- Gemstone (C-grade) -->
        <reNormal itemId="2131" count="89"/>    <!-- Gemstone (C-grade) -->
        <reSecondary itemId="2131" count="89"/>    <!-- Gemstone (C-grade) -->
        <reThird itemId="2131" count="89"/>    <!-- Gemstone (C-grade) -->
        <remove itemId="2131" count="89"/>    <!-- Gemstone (C-grade) -->
    </fee>

    <fee crystalType="B">
        <first itemId="2132" count="112"/> <!-- Gemstone (B-grade) -->
        <secondary itemId="2132" count="112"/> <!-- Gemstone (B-grade) -->
        <third itemId="2132" count="112"/> <!-- Gemstone (B-grade) -->
        <reNormal itemId="2132" count="56"/>    <!-- Gemstone (B-grade) -->
        <reSecondary itemId="2132" count="56"/>    <!-- Gemstone (B-grade) -->
        <reThird itemId="2132" count="56"/>    <!-- Gemstone (B-grade) -->
        <remove itemId="2132" count="19"/>    <!-- Gemstone (B-grade) -->
        <remove itemId="57" count="700000"/>    <!-- Adena -->
    </fee>
    <fee crystalType="A">
        <first itemId="2133" count="24"/> <!-- Gemstone (A-grade) -->
        <secondary itemId="2133" count="24"/> <!-- Gemstone (A-grade) -->
        <third itemId="2133" count="24"/> <!-- Gemstone (A-grade) -->
        <reNormal itemId="2133" count="12"/>    <!-- Gemstone (A-grade) -->
        <reSecondary itemId="2133" count="12"/>    <!-- Gemstone (A-grade) -->
        <reThird itemId="2133" count="12"/>    <!-- Gemstone (A-grade) -->
        <remove itemId="2133" count="5"/>    <!-- Gemstone (A-grade) -->
        <remove itemId="57" count="3500000"/>    <!-- Adena -->
    </fee>
	
	<!-- Installing Rune in weapons (245p - all) -->
    <stone id="29818" slotType="1">
        <option id="1"/>
        <option id="21"/>
    </stone>
    <stone id="29819" slotType="1">
        <option id="2"/>
        <option id="22"/>
    </stone>
    <stone id="29820" slotType="1">
        <option id="3"/>
        <option id="23"/>
    </stone>
    <stone id="29821" slotType="1">
        <option id="4"/>
        <option id="24"/>
    </stone>
    <stone id="29822" slotType="1">
        <option id="5"/>
        <option id="25"/>
    </stone>
    <stone id="29823" slotType="1">
        <option id="6"/>
        <option id="26"/>
    </stone>
    <stone id="29824" slotType="1">
        <option id="7"/>
        <option id="27"/>
    </stone>
    <stone id="29825" slotType="1">
        <option id="8"/>
        <option id="28"/>
    </stone>
    <stone id="29826" slotType="1">
        <option id="9"/>
        <option id="29"/>
    </stone>
    <stone id="29827" slotType="1">
        <option id="10"/>
        <option id="30"/>
    </stone>
    <stone id="29828" slotType="1">
        <option id="11"/>
        <option id="31"/>
    </stone>
    <stone id="29829" slotType="1">
        <option id="12"/>
        <option id="32"/>
    </stone>
    <stone id="29830" slotType="1">
        <option id="13"/>
        <option id="33"/>
    </stone>
    <stone id="29831" slotType="1">
        <option id="14"/>
        <option id="34"/>
    </stone>
    <stone id="29832" slotType="1">
        <option id="15"/>
        <option id="35"/>
    </stone>
    <stone id="29833" slotType="1">
        <option id="16"/>
        <option id="36"/>
    </stone>
    <stone id="29834" slotType="1">
        <option id="17"/>
        <option id="37"/>
    </stone>
    <stone id="29835" slotType="1">
        <option id="18"/>
        <option id="38"/>
    </stone>
    <stone id="29836" slotType="1">
        <option id="19"/>
        <option id="39"/>
    </stone>
    <stone id="29837" slotType="1">
        <option id="20"/>
        <option id="40"/>
    </stone>
    <stone id="29838" slotType="1">
        <option id="41"/>
        <option id="61"/>
    </stone>
    <stone id="29839" slotType="1">
        <option id="42"/>
        <option id="62"/>
    </stone>
    <stone id="29840" slotType="1">
        <option id="43"/>
        <option id="63"/>
    </stone>
    <stone id="29841" slotType="1">
        <option id="44"/>
        <option id="64"/>
    </stone>
    <stone id="29842" slotType="1">
        <option id="45"/>
        <option id="65"/>
    </stone>
    <stone id="29843" slotType="1">
        <option id="46"/>
        <option id="66"/>
    </stone>
    <stone id="29844" slotType="1">
        <option id="47"/>
        <option id="67"/>
    </stone>
    <stone id="29845" slotType="1">
        <option id="48"/>
        <option id="68"/>
    </stone>
    <stone id="29846" slotType="1">
        <option id="49"/>
        <option id="69"/>
    </stone>
    <stone id="29847" slotType="1">
        <option id="50"/>
        <option id="70"/>
    </stone>
    <stone id="29848" slotType="1">
        <option id="51"/>
        <option id="71"/>
    </stone>
    <stone id="29849" slotType="1">
        <option id="52"/>
        <option id="72"/>
    </stone>
    <stone id="29850" slotType="1">
        <option id="53"/>
        <option id="73"/>
    </stone>
    <stone id="29851" slotType="1">
        <option id="54"/>
        <option id="74"/>
    </stone>
    <stone id="29852" slotType="1">
        <option id="55"/>
        <option id="75"/>
    </stone>
    <stone id="29853" slotType="1">
        <option id="56"/>
        <option id="76"/>
    </stone>
    <stone id="29854" slotType="1">
        <option id="57"/>
        <option id="77"/>
    </stone>
    <stone id="29855" slotType="1">
        <option id="58"/>
        <option id="78"/>
    </stone>
    <stone id="29856" slotType="1">
        <option id="59"/>
        <option id="79"/>
    </stone>
    <stone id="29857" slotType="1">
        <option id="60"/>
        <option id="80"/>
    </stone>
    <stone id="29858" slotType="1">
        <option id="81"/>
        <option id="101"/>
    </stone>
    <stone id="29859" slotType="1">
        <option id="82"/>
        <option id="102"/>
    </stone>
    <stone id="29860" slotType="1">
        <option id="83"/>
        <option id="103"/>
    </stone>
    <stone id="29861" slotType="1">
        <option id="84"/>
        <option id="104"/>
    </stone>
    <stone id="29862" slotType="1">
        <option id="85"/>
        <option id="105"/>
    </stone>
    <stone id="29863" slotType="1">
        <option id="86"/>
        <option id="106"/>
    </stone>
    <stone id="29864" slotType="1">
        <option id="87"/>
        <option id="107"/>
    </stone>
    <stone id="29865" slotType="1">
        <option id="88"/>
        <option id="108"/>
    </stone>
    <stone id="29866" slotType="1">
        <option id="89"/>
        <option id="109"/>
    </stone>
    <stone id="29867" slotType="1">
        <option id="90"/>
        <option id="110"/>
    </stone>
    <stone id="29868" slotType="1">
        <option id="91"/>
        <option id="111"/>
    </stone>
    <stone id="29869" slotType="1">
        <option id="92"/>
        <option id="112"/>
    </stone>
    <stone id="29870" slotType="1">
        <option id="93"/>
        <option id="113"/>
    </stone>
    <stone id="29871" slotType="1">
        <option id="94"/>
        <option id="114"/>
    </stone>
    <stone id="29872" slotType="1">
        <option id="95"/>
        <option id="115"/>
    </stone>
    <stone id="29873" slotType="1">
        <option id="96"/>
        <option id="116"/>
    </stone>
    <stone id="29874" slotType="1">
        <option id="97"/>
        <option id="117"/>
    </stone>
    <stone id="29875" slotType="1">
        <option id="98"/>
        <option id="118"/>
    </stone>
    <stone id="29876" slotType="1">
        <option id="99"/>
        <option id="119"/>
    </stone>
    <stone id="29877" slotType="1">
        <option id="100"/>
        <option id="120"/>
    </stone>
    <stone id="29878" slotType="1">
        <option id="121"/>
        <option id="141"/>
    </stone>
    <stone id="29879" slotType="1">
        <option id="122"/>
        <option id="142"/>
    </stone>
    <stone id="29880" slotType="1">
        <option id="123"/>
        <option id="143"/>
    </stone>
    <stone id="29881" slotType="1">
        <option id="124"/>
        <option id="144"/>
    </stone>
    <stone id="29882" slotType="1">
        <option id="125"/>
        <option id="145"/>
    </stone>
    <stone id="29883" slotType="1">
        <option id="126"/>
        <option id="146"/>
    </stone>
    <stone id="29884" slotType="1">
        <option id="127"/>
        <option id="147"/>
    </stone>
    <stone id="29885" slotType="1">
        <option id="128"/>
        <option id="148"/>
    </stone>
    <stone id="29886" slotType="1">
        <option id="129"/>
        <option id="149"/>
    </stone>
    <stone id="29887" slotType="1">
        <option id="130"/>
        <option id="150"/>
    </stone>
    <stone id="29888" slotType="1">
        <option id="131"/>
        <option id="151"/>
    </stone>
    <stone id="29889" slotType="1">
        <option id="132"/>
        <option id="152"/>
    </stone>
    <stone id="29890" slotType="1">
        <option id="133"/>
        <option id="153"/>
