=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/xsd/LCoinShop.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://l2j.org" xmlns="http://l2j.org" elementFormDefault="qualified">
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="product" type="ProductInfo"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="Category">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Equip"/>
            <xs:enumeration value="Special"/>
            <xs:enumeration value="Supplies"/>
            <xs:enumeration value="Other"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ItemInfo">
        <xs:attribute name="id" type="xs:integer" use="required" />
        <xs:attribute name="count" type="xs:positiveInteger" default="1" />
    </xs:complexType>

    <xs:complexType name="ProductInfo">
        <xs:sequence>
            <xs:element name="ingredient" type="ItemInfo" maxOccurs="3"/>
            <xs:element name="production" type="ItemInfo"/>
        </xs:sequence>


        <xs:attribute name="id" type="xs:integer" use="required"/>
        <xs:attribute name="category" type="Category" use="required"/>
        <xs:attribute name="limitPerDay" type="xs:integer" default="0"/>
        <xs:attribute name="minLevel" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="isEvent" type="xs:boolean" default="0"/>
    </xs:complexType>

</xs:schema>

=== TokTil-Dev/L2jOrg/Datapack/gameserver/data/LCoinShop.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org xsd/LCoinShop.xsd" >
    <!-- 270 Prot, Roff -->
	<product id="10001" category="Equip">	<!--Пояс Дракона Земли-->
        <ingredient id="91663" count="1"/>
        <production id="90496"/>
    </product>
    <product id="10002" category="Equip">	<!--Пояс Дракона Огня-->
        <ingredient id="91663" count="1"/>
        <production id="90497"/>
    </product>
    <product id="10003" category="Equip">	<!--Плащ Эльморедена-->
        <ingredient id="91663" count="1"/>
        <production id="70877"/>
    </product>
    <product id="10004" category="Equip">	<!--Плащ Адена-->
        <ingredient id="91663" count="1"/>
        <production id="70878"/>
    </product>
    <product id="10005" category="Equip">	<!--Плащ Эльмора-->
        <ingredient id="91663" count="1"/>
        <production id="70879"/>
    </product>
    <product id="10006" category="Equip">	<!--Плащ Феррита-->
        <ingredient id="91663" count="1"/>
        <production id="70880"/>
    </product>
    <product id="10007" category="Equip">	<!--Легендарный Свиток-->
        <ingredient id="91663" count="1"/>
        <production id="70888"/>
    </product>
    <product id="10008" category="Equip">	<!--Свиток: Модифицировать Плащ-->
        <ingredient id="91663" count="1"/>
        <production id="70885"/>
    </product>
    <product id="10009" category="Equip">	<!--Свиток: Модифицировать Легендарный Плащ-->
        <ingredient id="91663" count="1"/>
        <production id="70886"/>
    </product>
    <product id="10010" category="Equip">	<!--Камень Жизни - Древнее Королевство-->
        <ingredient id="91663" count="1"/>
        <production id="70889"/>
    </product>
    <product id="10011" category="Equip">	<!--Сундук с Камнем Жизни Высокого Ранга - Плащ-->
        <ingredient id="91663" count="1"/>
        <production id="71132"/>
    </product>
    <product id="10012" category="Equip">	<!--Блестящий Ларец-->
        <ingredient id="91663" count="1"/>
        <production id="71436"/>
    </product>
    <product id="10013" category="Equip">	<!--Энергия Самоцвета-->
        <ingredient id="91663" count="1"/>
        <production id="71414"/>
    </product>
    <product id="10014" category="Equip">	<!--Набор Модификации: Талисман Адена-->
        <ingredient id="91663" count="1"/>
        <production id="91767"/>
    </product>
    <product id="10015" category="Equip">	<!--Набор Модификации: Талисман Евы-->
        <ingredient id="91663" count="1"/>
        <production id="92020"/>
    </product>
    <product id="10016" category="Equip">	<!--Осколок Талисмана Властителя-->
        <ingredient id="91663" count="1"/>
        <production id="71078"/>
    </product>
    <product id="10017" category="Equip">	<!--Купон на Обмен Агатиона-->
        <ingredient id="91663" count="1"/>
        <production id="91159"/>
    </product>
    <product id="10018" category="Equip">	<!--Свиток: Модифицировать Агатиона-->
        <ingredient id="91663" count="1"/>
        <production id="48046"/>
    </product>
    <product id="10019" category="Equip">	<!--Сундук с Душой Агатиона-->
        <ingredient id="91663" count="1"/>
        <production id="71855"/>
    </product>
    <product id="10020" category="Equip">	<!--Коробка Евы с Головными Уборами-->
        <ingredient id="91663" count="1"/>
        <production id="70758"/>
    </product>
    <product id="10021" category="Equip">	<!--Коробка Евы с Предметами для Модификации - Головной Убор-->
        <ingredient id="91663" count="1"/>
        <production id="70757"/>
    </product>
    <product id="10022" category="Equip">	<!--Эссенция Дракона-->
        <ingredient id="91663" count="1"/>
        <production id="71699"/>
    </product>
    <product id="10023" category="Special">	<!--Свиток Благословения Сторожевой Башни-->
        <ingredient id="91663" count="1"/>
        <production id="90835"/>
    </product>
    <product id="10024" category="Special">	<!--Свиток Битвы-->
        <ingredient id="91663" count="1"/>
        <production id="91780"/>
    </product>
    <product id="10025" category="Special">	<!--Свиток Эффектов Сайхи-->
        <ingredient id="91663" count="1"/>
        <production id="91781"/>
    </product>
    <product id="10026" category="Special">	<!--Купоны на Заряды Души-->
        <ingredient id="91663" count="1"/>
        <production id="90907"/>
    </product>
    <product id="10027" category="Special">	<!--Улучшенный Свиток Телепорта - Ивент-->
        <ingredient id="91663" count="1"/>
        <production id="91839"/>
    </product>
    <product id="10028" category="Special">	<!--Свиток Увеличения Опыта - Ивент-->
        <ingredient id="91663" count="1"/>
        <production id="91840"/>
    </product>
    <product id="10029" category="Suppliesl">	<!--Руна Анаким Ур. 1-->
        <ingredient id="91663" count="1"/>
        <production id="91163"/>
    </product>
    <product id="10030" category="Suppliesl">	<!--Руна Лилит Ур. 1-->
        <ingredient id="91663" count="1"/>
        <production id="91173"/>
    </product>
    <product id="10031" category="Suppliesl">	<!--Колчан с Бесконечными Стальными Стрелами-->
        <ingredient id="91663" count="1"/>
        <production id="32251"/>
    </product>
    <product id="10032" category="Suppliesl">	<!--Колчан с Бесконечными Серебряными Стрелами-->
        <ingredient id="91663" count="1"/>
        <production id="32252"/>
    </product>
    <product id="10033" category="Suppliesl">	<!--Колчан с Бесконечными Мифриловыми Стрелами-->
        <ingredient id="91663" count="1"/>
        <production id="32253"/>
    </product>
    <product id="10034" category="Suppliesl">	<!--Колчан с Бесконечными Сверкающими Стрелами-->
        <ingredient id="91663" count="1"/>
        <production id="32254"/>
    </product>
    <product id="10035" category="Suppliesl">	<!--Свиток: Модифицировать Оружие Ранга A-->
        <ingredient id="91663" count="1"/>
        <production id="70764"/>
    </product>
    <product id="10036" category="Suppliesl">	<!--Свиток: Модифицировать Доспех Ранга A-->
        <ingredient id="91663" count="1"/>
        <production id="70356"/>
    </product>
    <product id="10037" category="Suppliesl">	<!--Свиток: Модифицировать Оружие Ранга B-->
        <ingredient id="91663" count="1"/>
        <production id="93406"/>
    </product>
    <product id="10038" category="Suppliesl">	<!--Свиток: Модифицировать Доспех Ранга B-->
        <ingredient id="91663" count="1"/>
        <production id="93407"/>
    </product>
    <product id="10039" category="Suppliesl">	<!--Свиток: Модифицировать Оружие Ранга C-->
        <ingredient id="91663" count="1"/>
        <production id="93408"/>
    </product>
    <product id="10040" category="Suppliesl">	<!--Свиток: Модифицировать Доспех Ранга C-->
        <ingredient id="91663" count="1"/>
        <production id="93409"/>
    </product>
    <product id="10041" category="Other">	<!--Брошь Ур. 1-->
        <ingredient id="91663" count="1"/>
        <production id="90311"/>
    </product>
    <product id="10042" category="Other">	<!--Браслет для Талисманов Ур. 1-->
        <ingredient id="91663" count="1"/>
        <production id="9589"/>
    </product>
    <product id="10043" category="Other">	<!--Браслет Призыва Агатиона Ур. 1-->
        <ingredient id="91663" count="1"/>
        <production id="70929"/>
    </product>
    <product id="10044" category="Other">	<!--Набор Модификации: Талисман Адена-->
        <ingredient id="91663" count="1"/>
        <production id="91767"/>
    </product>
    <product id="10045" category="Other">	<!--Набор Модификации: Талисман Евы-->
        <ingredient id="91663" count="1"/>
        <production id="92020"/>
    </product>
    <product id="10046" category="Other">	<!--Купоны на Заряды Души-->
        <ingredient id="91663" count="1"/>
        <production id="90907"/>
    </product>
    <product id="10047" category="Other">	<!--Зелье Мафр-->
        <ingredient id="91663" count="1"/>
        <production id="91157"/>
    </product>
    <product id="10048" category="Other">	<!--Зелье Восстановления HP Героя - Ивент-->
        <ingredient id="91663" count="1"/>
        <production id="91843"/>
    </product>
    <product id="10049" category="Other">	<!--Зелье Восстановления МР Героя - Ивент-->
        <ingredient id="91663" count="1"/>
        <production id="91844"/>
    </product>
    <product id="10050" category="Other">	<!--Амулет Опыта Героя-->
        <ingredient id="91663" count="1"/>
        <production id="90836"/>
	</product>
</list>
